version: '3.3'
services:
  db:
    container_name: todolist_db
    image: mysql
    environment:
      MYSQL_DATABASE: 'todolist'
      # So you don't have to use root, but you can if you like
      # MYSQL_USER: 'root'
      # # You can use whatever password you like
      # MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql: